# Generated by Django 5.1.3 on 2025-02-09 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0002_alter_attendancesummary_options_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha_asignada']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
