# Generated by Django 5.1.3 on 2026-02-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=150, null=True, unique=True, verbose_name='Username normalizado'),
        ),
    ]
