# Generated by Django 5.1.3 on 2026-02-05 06:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_asociacion', '0007_alter_evento_descripcion_alter_evento_fecha_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_usuario_email_lower'),
        ),
    ]
