# Generated by Django 5.1.3 on 2026-02-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0009_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='en_papelera',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
