# Generated by Django 5.1.3 on 2026-03-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0012_bitacoraacceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Dios', 'Dios'), ('Administrador', 'Administrador'), ('Miembro', 'Miembro')], default='Miembro', max_length=50, verbose_name='Rol'),
        ),
    ]
