# Generated by Django 5.1.3 on 2026-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0013_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('sin_entrada', 'Sin entrada'), ('salida_pendiente', 'Salida pendiente'), ('asistencia_completa', 'Asistencia completa'), ('retardo', 'Retardo')], db_index=True, default='sin_entrada', max_length=30, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
