# Generated by Django 5.1.3 on 2026-05-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0014_asistencia_estado_asistencia_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('sin_entrada', 'Sin entrada'), ('salida_pendiente', 'Salida pendiente'), ('asistencia_completa', 'Asistencia completa'), ('salida_automatica', 'Salida automática'), ('retardo', 'Retardo')], db_index=True, default='sin_entrada', max_length=30, verbose_name='Estado'),
        ),
    ]
