# Generated by Django 5.1.3 on 2026-06-05 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0015_alter_asistencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración general', max_length=100, verbose_name='Nombre')),
                ('hora_entrada', models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de entrada')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=15, verbose_name='Tolerancia en minutos')),
                ('hora_salida_automatica', models.TimeField(default=datetime.time(23, 59), verbose_name='Hora de salida automática')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Configuración de asistencia',
                'verbose_name_plural': 'Configuraciones de asistencia',
            },
        ),
    ]
