# Generated by Django 5.1.3 on 2026-06-07 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0016_configuracionasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionasistencia',
            name='hora_limite_extraordinario',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Hora límite para registro extraordinario'),
        ),
    ]
