# Generated by Django 5.1.3 on 2026-07-02 02:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0017_configuracionasistencia_hora_limite_extraordinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionasistencia',
            name='hora_limite_extraordinario',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Hora límite para asistencia fuera de horario'),
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la capacitación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion_horas', models.PositiveIntegerField(default=1, verbose_name='Duración en horas')),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('En línea', 'En línea'), ('Mixta', 'Mixta')], default='Presencial', max_length=20, verbose_name='Modalidad')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], db_index=True, default='activa', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CapacitacionAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('fecha_realizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aprobada', 'Aprobada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('constancia', models.FileField(blank=True, null=True, upload_to='capacitaciones_constancias/%Y/%m/', verbose_name='Constancia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='gestion_asociacion.capacitacion', verbose_name='Capacitación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario asignado')),
            ],
            options={
                'verbose_name': 'Capacitación asignada',
                'verbose_name_plural': 'Capacitaciones asignadas',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(fields=('capacitacion', 'usuario'), name='uniq_capacitacion_usuario')],
            },
        ),
    ]
