# Generated by Django 5.1.3 on 2026-07-03 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_asociacion', '0018_alter_configuracionasistencia_hora_limite_extraordinario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del material')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='capacitaciones_materiales/%Y/%m/', verbose_name='Archivo')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace externo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='gestion_asociacion.capacitacion', verbose_name='Capacitación')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_capacitacion_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Material de capacitación',
                'verbose_name_plural': 'Materiales de capacitación',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
